[global.tls]
certs = "cert.pem"
key = "key.pem"

[development]
address = "localhost"
port = 8000
log = "normal"
secret_key = "u4shYQ/3Jm6+vh5QZsy4oX84rHDcS3/RDOgUEAL0p4M="

[production]
address = "localhost"
port = 8000
log = "critical"
secret_key = "u4shYQ/3Jm6+vh5QZsy4oX84rHDcS3/RDOgUEAL0p4M="
